platform :ios, '11.0'
use_frameworks!
target 'Piano_App' do

# Pods for Piano_App
	pod 'Firebase/Core'
	pod 'Firebase/Database'
  pod 'Firebase/Auth'
	pod 'FBSDKCoreKit'
	pod 'FBSDKLoginKit'
	pod 'FBSDKShareKit'

#  pod "Koloda"
#  pod "GSKStretchyHeaderView"
  pod 'RealmSwift', '5.3.5'
  pod 'IQKeyboardManagerSwift'
  pod 'DateToolsSwift'
  pod "ESTabBarController-swift"
  pod 'Kingfisher', '5.12.0'
  pod 'youtube-ios-player-helper'
  pod 'SDWebImage'
  pod 'Hero'
  pod 'lottie-ios'
  pod 'YoutubeKit'
  pod 'Shimmer', '1.0.2'
  pod 'IGListKit', '3.4.0'
  pod 'ModelMapper', '7.1.0'
  pod 'RxSwift', '4.5.0'
  pod 'RxCocoa', '4.5.0'
  pod 'PINRemoteImage', :git => 'https://github.com/Pinterest/PINRemoteImage.git', :tag => '3.0.0-beta.14'
  pod 'PINRemoteImage/WebP', :git => 'https://github.com/Pinterest/PINRemoteImage.git', :tag => '3.0.0-beta.14'
#  pod 'PINCache'
#  pod 'Siren', :git => 'https://github.com/ArtSabintsev/Siren.git', :branch => 'swift4.2'
  pod 'DTCoreText', '1.6.23'
  pod 'Alamofire', '4.9.0'
  pod 'Alamofire-SwiftyJSON', '3.0.0'
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'SVProgressHUD'
  pod 'FirebaseStorage'
  pod 'Firebase/Analytics'
  pod "FDWaveformView"
  pod 'ModernAVPlayer'
#  pod 'UICircularProgressRing'

#  pod 'AlamofireNetworkActivityIndicator', '2.4.0'
#  pod 'AlamofireImage', '3.5.2'
end
